### ISSUE TITLE
Custom styles

### ISSUE THREAD

**Issue by psico-digital** [mathieustan/vue-notification#1]
Great job @mathieustan!

What is the best way to customize styles, like colors, border-radius and font styles, to match my branding?

**Comment by mathieustan** [comment]
Hello @psico-digital. Thank you 😉

Actually, you can surcharge css. 
But I’ll add props to edit styles. I think it’s a good idea. 

I’m in holidays, so, I’ll do it when i’ll come back home 👍

**Comment by psico-digital** [comment]
Global props would be nice! Ok @mathieustan, enjoy your holidays 😊

**Comment by mathieustan** [comment]
Hello @psico-digital, 
I just added a new pre release [v0.1.3-rc.1](https://github.com/mathieustan/vue-notification/releases/tag/0.1.3-rc.1) which allow to configure theme.

Let me know what do you think.

**Comment by psico-digital** [comment]
Thanks @mathieustan! The rest of the customization we got by changing css directly.
