### ISSUE TITLE
Type offline improvement suggestion

### ISSUE THREAD

**Issue by psico-digital** [mathieustan/vue-notification#2]
I have a suggestion for `type: 'offline'`. See if it makes sense:

When offline, notification is expected to be shown until the connection is recovered. So I think it would be interesting to make `type: 'offline'` persistent, and then we call a function to close the notification.

```
if (isOffline) {
  this.$notify({ type: 'offline', message:  'Offline' }) // Persistent notification
} else {
  this.$notify.closeOffline() // Or something like this
}
```

**Comment by mathieustan** [comment]
Hello, 

Yes, it makes sense, but currently you can set notification persistent with `closedelay: 0`. Offline type is only for icon but maybe I'll change that later. 

Example: 
```
this.$notify.offline({ message: 'offline', closeDelay: 0 })
// then, you can close all notifications when you are back online 
this.$notify.closeAll();
```

**Comment by psico-digital** [comment]
Nice, that's what I needed. Thanks!
